### ISSUE TITLE
Fix usage in help text

### ISSUE THREAD

**Issue by snayfach** [zjshi/Maast#2]
Currently "usage: Maast.py  <module> [options]" but should be "usage: maast  <module> [options]"

**Comment by zjshi** [comment]
Good catch, fixed now.

**Comment by snayfach** [comment]
Not fixed for ant of the individual modules: `./maast end_to_end`

**Comment by zjshi** [comment]
This is seemingly due to the default error message of argparse. Not sure if there is a easy way to change it. I changed the name of Maast.py to maast.py to make it less obvious. Let me know please if you have a better way.
